int checkModifiers(int input){
  switch(input){
    case 17: //CTRL
      return KEYBOARD_MODIFIER_LEFTCTRL;
    case 16: //Shift
      return KEYBOARD_MODIFIER_LEFTSHIFT;
    case 18: //ALT
      return KEYBOARD_MODIFIER_LEFTALT;
    case 91: //Left GUI
      return KEYBOARD_MODIFIER_LEFTGUI;
    case 92: //Right GUI
      return KEYBOARD_MODIFIER_RIGHTGUI;
  }
  return 0;
}

int convertKeycode(int input){ //Convert keycodeds from: https://keycode-visualizer.netlify.app/ to Keycodes from: https://github.com/hathach/tinyusb/blob/master/src/class/hid/hid.h
  switch(input){
    case 8:
      return HID_KEY_BACKSPACE;
    case 9:
      return HID_KEY_TAB;
    case 13:
      return HID_KEY_ENTER;
    case 19:
      return HID_KEY_PAUSE;
    case 20:
      return HID_KEY_CAPS_LOCK;
    case 27:
      return HID_KEY_ESCAPE;
    case 32:
      return HID_KEY_SPACE;
    case 33:
      return HID_KEY_PAGE_UP;
    case 34:
      return HID_KEY_PAGE_DOWN;
    case 35:
      return HID_KEY_END;
    case 36:
      return HID_KEY_HOME;
    case 37:
      return HID_KEY_ARROW_LEFT;
    case 38:
      return HID_KEY_ARROW_UP;
    case 39:
      return HID_KEY_ARROW_RIGHT;
    case 40:
      return HID_KEY_ARROW_DOWN;
    case 45:
      return HID_KEY_INSERT;
    case 46:
      return HID_KEY_DELETE;
    case 48:
      return HID_KEY_0;
    case 49:
      return HID_KEY_1;
    case 50:
      return HID_KEY_2;
    case 51:
      return HID_KEY_3;
    case 52:
      return HID_KEY_4;
    case 53:
      return HID_KEY_5;
    case 54:
      return HID_KEY_6;
    case 55:
      return HID_KEY_7;
    case 56:
      return HID_KEY_8;
    case 57:
      return HID_KEY_9;
    case 65:
      return HID_KEY_A;
    case 66:
      return HID_KEY_B;
    case 67:
      return HID_KEY_C;
    case 68:
      return HID_KEY_D;
    case 69:
      return HID_KEY_E;
    case 70:
      return HID_KEY_F;
    case 71:
      return HID_KEY_G;
    case 72:
      return HID_KEY_H;
    case 73:
      return HID_KEY_I;
    case 74:
      return HID_KEY_J;
    case 75:
      return HID_KEY_K;
    case 76:
      return HID_KEY_L;
    case 77:
      return HID_KEY_M;
    case 78:
      return HID_KEY_N;
    case 79:
      return HID_KEY_O;
    case 80:
      return HID_KEY_P;
    case 81:
      return HID_KEY_Q;
    case 82:
      return HID_KEY_R;
    case 83:
      return HID_KEY_S;
    case 84:
      return HID_KEY_T;
    case 85:
      return HID_KEY_U;
    case 86:
      return HID_KEY_V;
    case 87:
      return HID_KEY_W;
    case 88:
      return HID_KEY_X;
    case 89:
      return HID_KEY_Y;
    case 90:
      return HID_KEY_Z;
    case 96:
      return HID_KEY_KEYPAD_0;
    case 97:
      return HID_KEY_KEYPAD_1;
    case 98:
      return HID_KEY_KEYPAD_2;
    case 99:
      return HID_KEY_KEYPAD_3;
    case 100:
      return HID_KEY_KEYPAD_4;
    case 101:
      return HID_KEY_KEYPAD_5;
    case 102:
      return HID_KEY_KEYPAD_6;
    case 103:
      return HID_KEY_KEYPAD_7;
    case 104:
      return HID_KEY_KEYPAD_8;
    case 105:
      return HID_KEY_KEYPAD_9;
    case 106:
      return HID_KEY_KEYPAD_MULTIPLY;
    case 107:
      return HID_KEY_KEYPAD_ADD;
    case 109:
      return HID_KEY_KEYPAD_SUBTRACT;
    case 110:
      return HID_KEY_KEYPAD_DECIMAL;
    case 111:
      return HID_KEY_KEYPAD_DIVIDE;
    case 112:
      return HID_KEY_F1;
    case 113:
      return HID_KEY_F2;
    case 114:
      return HID_KEY_F3;
    case 115:
      return HID_KEY_F4;
    case 116:
      return HID_KEY_F5;
    case 117:
      return HID_KEY_F6;
    case 118:
      return HID_KEY_F7;
    case 119:
      return HID_KEY_F8;
    case 120:
      return HID_KEY_F9;
    case 121:
      return HID_KEY_F10;
    case 122:
      return HID_KEY_F11;
    case 123:
      return HID_KEY_F12;
    case 144:
      return HID_KEY_NUM_LOCK;
    case 145:
      return HID_KEY_SCROLL_LOCK;
    case 173:
      return HID_KEY_MUTE;
    case 174:
      return HID_KEY_VOLUME_DOWN;
    case 175:
      return HID_KEY_VOLUME_UP;
    case 186:
      return HID_KEY_SEMICOLON;
    case 187:
      return HID_KEY_EQUAL;
    case 188:
      return HID_KEY_COMMA;
    case 189:
      return HID_KEY_MINUS;
    case 190:
      return HID_KEY_PERIOD;
    case 191:
      return HID_KEY_SLASH;
    case 192:
      return HID_KEY_GRAVE;
    case 219:
      return HID_KEY_BRACKET_LEFT;
    case 220:
      return HID_KEY_BACKSLASH;
    case 221:
      return HID_KEY_BRACKET_RIGHT;
    case 222:
      return HID_KEY_APOSTROPHE;

  }
  return 0;
}